#Template generated on 2016-10-13 17:18:36 +0100
#Do not edit this file. Modify the relevant config and regenerate

require 'digest'

class AssemblyMapping < Formula
  url 'file://'+File.expand_path(__FILE__)
  desc 'Dependencies for the AssemblyMapping formula'
  sha256 Digest::SHA256.file(File.expand_path(__FILE__)).hexdigest
  version '1'

  depends_on 'homebrew/science/lastz'
  depends_on 'ensembl/ensembl/kent'

  def install
    File.open('assembly-mapping', 'w') { |file|
      file.write '#!/bin/sh'+"\n"
      deps.each do | dep |
        f = dep.to_formula
        file.write "echo "+[f.full_name, f.version, f.prefix].join("\t")+"\n"
      end
    }
    bin.install 'assembly-mapping'
  end
end
    