#Template generated on 2018-01-05 11:46:38 +0000
#Do not edit this file. Modify the relevant config and regenerate

require 'digest'

class AssemblyMapping < Formula
  url 'file://'+File.expand_path(__FILE__)
  desc 'Dependencies for the AssemblyMapping formula'
  sha256 Digest::SHA256.file(File.expand_path(__FILE__)).hexdigest
  version '2'

  depends_on 'ensembl/external/lastz'
  depends_on 'ensembl/external/kent'

  def install
    File.open('assembly-mapping', 'w') { |file|
      file.write '#!/bin/sh'+"\n"
      deps.each do | dep |
        f = dep.to_formula
        file.write "echo "+[f.full_name, f.version, f.prefix].join("\t")+"\n"
      end
    }
    bin.install 'assembly-mapping'
  end
end
    