#Template generated on Mon Jul 18 12:29:43 +0100 2016
#Do not edit this file. Modify the relevant config and regenerate
require 'digest'
class AssemblyMapping < Formula
  url 'file://'+File.expand_path(__FILE__)
  desc 'Dependencies for the AssemblyMapping formula'
  sha256 Digest::SHA256.file(File.expand_path(__FILE__)).hexdigest
  version '1'

  depends_on 'homebrew/science/lastz'

  depends_on 'ensembl/ensembl/kent'

  def install
    File.open('assembly-mapping', 'w') { |file|
      file.write '#!/bin/sh'+"\n"
      deps.each do | dep |
        f = dep.to_formula
        file.write "echo "+[f.full_name, f.version, f.prefix].join("\t")+"\n"
      end
    }
    bin.install 'assembly-mapping'
  end
end
    