#Template generated on 2017-07-25 13:24:14 +0100
#Do not edit this file. Modify the relevant config and regenerate

require 'digest'

class BasicDependenciesFromSource < Formula
  url 'file://'+File.expand_path(__FILE__)
  desc 'Dependencies for the BasicDependenciesFromSource formula'
  sha256 Digest::SHA256.file(File.expand_path(__FILE__)).hexdigest
  version '2'

  depends_on 'gettext'
  depends_on 'pcre'

  def install
    File.open('basic-dependencies-from-source', 'w') { |file|
      file.write '#!/bin/sh'+"\n"
      deps.each do | dep |
        f = dep.to_formula
        file.write "echo "+[f.full_name, f.version, f.prefix].join("\t")+"\n"
      end
    }
    bin.install 'basic-dependencies-from-source'
  end
end
    