#Template generated on 2016-07-27 17:45:14 +0100
#Do not edit this file. Modify the relevant config and regenerate
require 'digest'
class BasicDependencies < Formula
  url 'file://'+File.expand_path(__FILE__)
  desc 'Dependencies for the BasicDependencies formula'
  sha256 Digest::SHA256.file(File.expand_path(__FILE__)).hexdigest
  version '1'

  depends_on 'git'

  depends_on 'ack'

  depends_on 'jdk'

  def install
    File.open('basic-dependencies', 'w') { |file|
      file.write '#!/bin/sh'+"\n"
      deps.each do | dep |
        f = dep.to_formula
        file.write "echo "+[f.full_name, f.version, f.prefix].join("\t")+"\n"
      end
    }
    bin.install 'basic-dependencies'
  end
end
    