#Template generated on 2017-07-12 18:32:22 +0100
#Do not edit this file. Modify the relevant config and regenerate

require 'digest'

class ComparaLastz < Formula
  url 'file://'+File.expand_path(__FILE__)
  desc 'Dependencies for the ComparaLastz formula'
  sha256 Digest::SHA256.file(File.expand_path(__FILE__)).hexdigest
  version '0.1'

  depends_on 'homebrew/science/lastz'
  depends_on 'ensembl/ensembl/kent'

  def install
    File.open('compara-lastz', 'w') { |file|
      file.write '#!/bin/sh'+"\n"
      deps.each do | dep |
        f = dep.to_formula
        file.write "echo "+[f.full_name, f.version, f.prefix].join("\t")+"\n"
      end
    }
    bin.install 'compara-lastz'
  end
end
    