#Template generated on 2017-07-12 18:41:04 +0100
#Do not edit this file. Modify the relevant config and regenerate

require 'digest'

class ComparaProteintrees < Formula
  url 'file://'+File.expand_path(__FILE__)
  desc 'Dependencies for the ComparaProteintrees formula'
  sha256 Digest::SHA256.file(File.expand_path(__FILE__)).hexdigest
  version '0.1'

  depends_on 'homebrew/science/hmmer'
  depends_on 'homebrew/science/hmmer2'
  depends_on 'ensembl/ensembl/blast'
  depends_on 'homebrew/science/mafft'
  depends_on 'ensembl/ensembl/t-coffee'
  depends_on 'ensembl/ensembl/hclustersg'
  depends_on 'ensembl/ensembl/treebest'
  depends_on 'homebrew/science/quicktree'
  depends_on 'ensembl/ensembl/paml43'
  depends_on 'ensembl/ensembl/ktreedist'
  depends_on 'ensembl/ensembl/raxml-get-patterns'
  depends_on 'ensembl/ensembl/noisy'
  depends_on 'ensembl/ensembl/notung'
  depends_on 'ensembl/ensembl/fasttree'
  depends_on 'ensembl/ensembl/prottest3'
  depends_on 'homebrew/science/trimal'
  depends_on 'ensembl/ensembl/cafe'
  depends_on 'homebrew/science/cd-hit'
  depends_on 'ensembl/ensembl/pantherscore'

  def install
    File.open('compara-proteintrees', 'w') { |file|
      file.write '#!/bin/sh'+"\n"
      deps.each do | dep |
        f = dep.to_formula
        file.write "echo "+[f.full_name, f.version, f.prefix].join("\t")+"\n"
      end
    }
    bin.install 'compara-proteintrees'
  end
end
    