#Template generated on 2016-11-21 12:00:06 +0000
#Do not edit this file. Modify the relevant config and regenerate

require 'digest'

class ComparaTeam < Formula
  url 'file://'+File.expand_path(__FILE__)
  desc 'Dependencies for the ComparaTeam formula'
  sha256 Digest::SHA256.file(File.expand_path(__FILE__)).hexdigest
  version '0.1'

  depends_on 'ensembl/ensembl/exonerate22'
  depends_on 'homebrew/homebrew-science/infernal.rb'
  depends_on 'homebrew/homebrew-science/hmmer.rb'
  depends_on 'homebrew/homebrew-science/hmmer2.rb'
  depends_on 'ensembl/homebrew-ensembl/blast.rb'
  depends_on 'homebrew/homebrew-science/mafft.rb'
  depends_on 'ensembl/homebrew-ensembl/t-coffee.rb'
  depends_on 'ensembl/homebrew-ensembl/hclustersg.rb'
  depends_on 'ensembl/homebrew-ensembl/treebest.rb'
  depends_on 'ensembl/homebrew-ensembl/quicktree.rb'
  depends_on 'homebrew/homebrew-core/Formula/codemod.rb'
  depends_on 'ensembl/homebrew-ensembl/ktreedist.rb'
  depends_on 'ensembl/homebrew-icc/raxml.rb'
  depends_on 'ensembl/homebrew-ensembl/raxml-get-patterns.rb'
  depends_on 'ensembl/homebrew-icc/examl.rb'
  depends_on 'ensembl/homebrew-ensembl/noisy.rb'
  depends_on 'ensembl/homebrew-ensembl/notung.rb'
  depends_on 'ensembl/homebrew-ensembl/notung.rb'
  depends_on 'ensembl/homebrew-ensembl/pecan.rb'
  depends_on 'ensembl/homebrew-ensembl/ortheus.rb'
  depends_on 'ensembl/homebrew-ensembl/fasttree.rb'
  depends_on 'ensembl/homebrew-ensembl/prottest3.rb'
  depends_on 'homebrew/homebrew-science/trimal.rb'
  depends_on 'ensembl/homebrew-ensembl/badirate.rb'
  depends_on 'ensembl/homebrew-ensembl/cafe.rb'
  depends_on 'ensembl/homebrew-ensembl/gerp.rb'
  depends_on 'homebrew/homebrew-science/mcl.rb'
  depends_on 'ensembl/homebrew-ensembl/prank.rb'
  depends_on 'ensembl/homebrew-ensembl/r2r.rb'
  depends_on 'ensembl/homebrew-ensembl/phast.rb'
  depends_on 'homebrew/homebrew-science/lastz.rb'
  depends_on 'ensembl/homebrew-ensembl/kent.rb'
  depends_on 'homebrew/homebrew-science/blat.rb'
  depends_on 'ensembl/homebrew-ensembl/parsimonator.rb'

  def install
    File.open('compara-team', 'w') { |file|
      file.write '#!/bin/sh'+"\n"
      deps.each do | dep |
        f = dep.to_formula
        file.write "echo "+[f.full_name, f.version, f.prefix].join("\t")+"\n"
      end
    }
    bin.install 'compara-team'
  end
end
    