#Template generated on 2016-07-28 14:08:28 +0100
#Do not edit this file. Modify the relevant config and regenerate
require 'digest'
class CrossReferences < Formula
  url 'file://'+File.expand_path(__FILE__)
  desc 'Dependencies for the CrossReferences formula'
  sha256 Digest::SHA256.file(File.expand_path(__FILE__)).hexdigest
  version '1'

  depends_on 'ensembl/ensembl/exonerate22'

  def install
    File.open('cross-references', 'w') { |file|
      file.write '#!/bin/sh'+"\n"
      deps.each do | dep |
        f = dep.to_formula
        file.write "echo "+[f.full_name, f.version, f.prefix].join("\t")+"\n"
      end
    }
    bin.install 'cross-references'
  end
end
    