#Template generated on 2018-01-05 11:31:22 +0000
#Do not edit this file. Modify the relevant config and regenerate

require 'digest'

class CrossReferences < Formula
  url 'file://'+File.expand_path(__FILE__)
  desc 'Dependencies for the CrossReferences formula'
  sha256 Digest::SHA256.file(File.expand_path(__FILE__)).hexdigest
  version '2'

  depends_on 'ensembl/external/exonerate22'

  def install
    File.open('cross-references', 'w') { |file|
      file.write '#!/bin/sh'+"\n"
      deps.each do | dep |
        f = dep.to_formula
        file.write "echo "+[f.full_name, f.version, f.prefix].join("\t")+"\n"
      end
    }
    bin.install 'cross-references'
  end
end
    