#Template generated on 2017-01-06 15:55:29 +0000
#Do not edit this file. Modify the relevant config and regenerate

require 'digest'

class EgCoreStats < Formula
  url 'file://'+File.expand_path(__FILE__)
  desc 'Dependencies for the EgCoreStats formula'
  sha256 Digest::SHA256.file(File.expand_path(__FILE__)).hexdigest
  version '1'

  depends_on 'ensembl/ensembl/emboss'

  def install
    File.open('eg-core-stats', 'w') { |file|
      file.write '#!/bin/sh'+"\n"
      deps.each do | dep |
        f = dep.to_formula
        file.write "echo "+[f.full_name, f.version, f.prefix].join("\t")+"\n"
      end
    }
    bin.install 'eg-core-stats'
  end
end
    