#Template generated on 2018-01-05 11:31:22 +0000
#Do not edit this file. Modify the relevant config and regenerate

require 'digest'

class EgMaker < Formula
  url 'file://'+File.expand_path(__FILE__)
  desc 'Dependencies for the EgMaker formula'
  sha256 Digest::SHA256.file(File.expand_path(__FILE__)).hexdigest
  version '5'

  depends_on 'gsl'
  depends_on 'suite-sparse'
  depends_on 'ensembl/external/lp_solve'
  depends_on 'ensembl/external/augustus'
  depends_on 'ensembl/external/exonerate22'
  depends_on 'ensembl/external/blast'
  depends_on 'ensembl/external/repeatmasker'
  depends_on 'ensembl/external/snap'
  depends_on 'ensembl/external/maker'

  def install
    File.open('eg-maker', 'w') { |file|
      file.write '#!/bin/sh'+"\n"
      deps.each do | dep |
        f = dep.to_formula
        file.write "echo "+[f.full_name, f.version, f.prefix].join("\t")+"\n"
      end
    }
    bin.install 'eg-maker'
  end
end
    