#Template generated on Mon Jul 04 15:59:25 +0100 2016
#Do not edit this file. Modify the relevant config and regenerate
require 'digest'
class EnsemblCore < Formula
  url 'file://'+File.expand_path(__FILE__)
  desc 'Dependencies for the EnsemblCore formula'
  sha256 Digest::SHA256.file(File.expand_path(__FILE__)).hexdigest
  version '1'

  depends_on 'ensembl/ensembl/exonerate22'

  depends_on 'homebrew/science/lastz'

  depends_on 'jdk'

  def install
    File.open('ensembl-core', 'w') { |file|
      file.write '#!/bin/sh'+"\n"
      deps.each do | dep |
        f = dep.to_formula
        file.write "echo "+[f.full_name, f.version, f.path].join("\t")+"\n"
      end
    }
    bin.install 'ensembl-core'
  end
end
    