#Template generated on 2018-07-05 11:09:55 +0100
#Do not edit this file. Modify the relevant config and regenerate

require 'digest'

class Funcgen < Formula
  url 'file://'+File.expand_path(__FILE__)
  desc 'Dependencies for the Funcgen formula'
  sha256 Digest::SHA256.file(File.expand_path(__FILE__)).hexdigest
  version '0.2'

  depends_on 'ensembl/ensembl/moods'
  depends_on 'ensembl/ensembl/biosd'

  def install
    File.open('funcgen', 'w') { |file|
      file.write '#!/bin/sh'+"\n"
      deps.each do | dep |
        f = dep.to_formula
        file.write "echo "+[f.full_name, f.version, f.prefix].join("\t")+"\n"
      end
    }
    bin.install 'funcgen'
  end
end
    