#Template generated on 2017-07-19 13:11:49 +0100
#Do not edit this file. Modify the relevant config and regenerate

require 'digest'

class Icc < Formula
  url 'file://'+File.expand_path(__FILE__)
  desc 'Dependencies for the Icc formula'
  sha256 Digest::SHA256.file(File.expand_path(__FILE__)).hexdigest
  version '1'

  depends_on 'ensembl/icc/examl'
  depends_on 'ensembl/icc/raxml'

  def install
    File.open('icc', 'w') { |file|
      file.write '#!/bin/sh'+"\n"
      deps.each do | dep |
        f = dep.to_formula
        file.write "echo "+[f.full_name, f.version, f.prefix].join("\t")+"\n"
      end
    }
    bin.install 'icc'
  end
end
    