#Template generated on Tue Jul 24 11:30:32 +0100 2018
#Do not edit this file. Modify the relevant config and regenerate

require 'digest'

class Parasite < Formula
  url 'file://'+File.expand_path(__FILE__)
  desc 'Dependencies for the Parasite formula'
  sha256 Digest::SHA256.file(File.expand_path(__FILE__)).hexdigest
  version '1'

  depends_on 'mysql-utilities'

  def install
    File.open('parasite', 'w') { |file|
      file.write '#!/bin/sh'+"\n"
      deps.each do | dep |
        f = dep.to_formula
        file.write "echo "+[f.full_name, f.version, f.prefix].join("\t")+"\n"
      end
    }
    bin.install 'parasite'
  end
end
    