#Template generated on 2021-07-14 14:25:09 +0100
#Do not edit this file. Modify the relevant config and regenerate

require 'digest'

class ProductionBiomart < Formula
  url 'file://'+File.expand_path(__FILE__)
  desc 'Dependencies for the ProductionBiomart formula'
  sha256 Digest::SHA256.file(File.expand_path(__FILE__)).hexdigest
  version '4'

  depends_on 'ensembl/web/httpd22'
  depends_on 'ensembl/web/mod_perl'

  def install
    File.open('production-biomart', 'w') { |file|
      file.write '#!/bin/sh'+"\n"
      deps.each do | dep |
        f = dep.to_formula
        file.write "echo "+[f.full_name, f.version, f.prefix].join("\t")+"\n"
      end
    }
    bin.install 'production-biomart'
  end
end
    