#Template generated on 2016-11-17 11:04:12 +0000
#Do not edit this file. Modify the relevant config and regenerate

require 'digest'

class RnaseqPipeline < Formula
  url 'file://'+File.expand_path(__FILE__)
  desc 'Dependencies for the RnaseqPipeline formula'
  sha256 Digest::SHA256.file(File.expand_path(__FILE__)).hexdigest
  version '1'

  depends_on 'ensembl/ensembl/samtools'
  depends_on 'ensembl/ensembl/exonerate09'
  depends_on 'ensembl/ensembl/bwa-051mt'
  depends_on 'ensembl/ensembl/ensc'
  depends_on 'ensembl/ensembl/picard-tools'
  depends_on 'ensembl/ensembl/bioperl-161'
  depends_on 'ensembl/ensembl/blast'

  def install
    File.open('rnaseq-pipeline', 'w') { |file|
      file.write '#!/bin/sh'+"\n"
      deps.each do | dep |
        f = dep.to_formula
        file.write "echo "+[f.full_name, f.version, f.prefix].join("\t")+"\n"
      end
    }
    bin.install 'rnaseq-pipeline'
  end
end
    