#Template generated on 2017-10-20 15:16:23 +0100
#Do not edit this file. Modify the relevant config and regenerate

require 'digest'

class WebBifo < Formula
  url 'file://'+File.expand_path(__FILE__)
  desc 'Dependencies for the WebBifo formula'
  sha256 Digest::SHA256.file(File.expand_path(__FILE__)).hexdigest
  version '1'

  depends_on 'homebrew/science/genewise'
  depends_on 'homebrew/science/emboss'
  depends_on 'homebrew/science/samtools'
  depends_on 'ensembl/ensembl/r2r'
  depends_on 'ensembl/ensembl/hal'
  depends_on 'ensembl/ensembl/bioperl-169'
  depends_on 'ensembl/ensembl/blast'
  depends_on 'ensembl/ensembl/repeatmasker' => ["with-perl", "with-dfam", "without-phrap", "without-repbase"]

  def install
    File.open('web-bifo', 'w') { |file|
      file.write '#!/bin/sh'+"\n"
      deps.each do | dep |
        f = dep.to_formula
        file.write "echo "+[f.full_name, f.version, f.prefix].join("\t")+"\n"
      end
    }
    bin.install 'web-bifo'
  end
end
    