#Template generated on 2017-11-02 17:05:30 +0000
#Do not edit this file. Modify the relevant config and regenerate

require 'digest'

class WebPerllibs < Formula
  url 'file://'+File.expand_path(__FILE__)
  desc 'Dependencies for the WebPerllibs formula'
  sha256 Digest::SHA256.file(File.expand_path(__FILE__)).hexdigest
  version '1'

  depends_on 'ensembl/ensembl/percona-client'
  depends_on 'ensembl/web/mod_perl'
  depends_on 'memcached'
  depends_on 'ensembl/ensembl/kent'
  depends_on 'htslib'

  def install
    File.open('web-perllibs', 'w') { |file|
      file.write '#!/bin/sh'+"\n"
      deps.each do | dep |
        f = dep.to_formula
        file.write "echo "+[f.full_name, f.version, f.prefix].join("\t")+"\n"
      end
    }
    bin.install 'web-perllibs'
  end
end
    