#Template generated on 2018-08-01 11:35:01 +0100
#Do not edit this file. Modify the relevant config and regenerate

require 'digest'

class WebInternal < Formula
  url 'file://'+File.expand_path(__FILE__)
  desc 'Dependencies for the WebInternal formula'
  sha256 Digest::SHA256.file(File.expand_path(__FILE__)).hexdigest
  version '1'

  depends_on 'ruby'
  depends_on 'ensembl/ensembl/ensembl-git-tools'

  def install
    File.open('web-internal', 'w') { |file|
      file.write '#!/bin/sh'+"\n"
      deps.each do | dep |
        f = dep.to_formula
        file.write "echo "+[f.full_name, f.version, f.prefix].join("\t")+"\n"
      end
    }
    bin.install 'web-internal'
  end
end
    