#Template generated on 2018-08-03 14:53:09 +0100
#Do not edit this file. Modify the relevant config and regenerate

require 'digest'

class WebLibsforcpanm < Formula
  url 'file://'+File.expand_path(__FILE__)
  desc 'Dependencies for the WebLibsforcpanm formula'
  sha256 Digest::SHA256.file(File.expand_path(__FILE__)).hexdigest
  version '2'

  depends_on 'ensembl/external/percona-client'
  depends_on 'ensembl/web/mod_perl'
  depends_on 'memcached'
  depends_on 'ensembl/external/kent'
  depends_on 'htslib'

  def install
    File.open('web-libsforcpanm', 'w') { |file|
      file.write '#!/bin/sh'+"\n"
      deps.each do | dep |
        f = dep.to_formula
        file.write "echo "+[f.full_name, f.version, f.prefix].join("\t")+"\n"
      end
    }
    bin.install 'web-libsforcpanm'
  end
end
    