#Template generated on 2018-08-09 14:01:00 +0100
#Do not edit this file. Modify the relevant config and regenerate

require 'digest'

class WebInternal < Formula
  url 'file://'+File.expand_path(__FILE__)
  desc 'Dependencies for the WebInternal formula'
  sha256 Digest::SHA256.file(File.expand_path(__FILE__)).hexdigest
  version '2'

  depends_on 'ruby'
  depends_on 'ensembl/ensembl/ensembl-git-tools'
  depends_on 'plenv'
  depends_on 'libxml2'
  depends_on 'socat'
  depends_on 'xerces-c'
  depends_on 'corkscrew'

  def install
    File.open('web-internal', 'w') { |file|
      file.write '#!/bin/sh'+"\n"
      deps.each do | dep |
        f = dep.to_formula
        file.write "echo "+[f.full_name, f.version, f.prefix].join("\t")+"\n"
      end
    }
    bin.install 'web-internal'
  end
end
    