#Template generated on 2017-10-20 15:16:23 +0100
#Do not edit this file. Modify the relevant config and regenerate

require 'digest'

class WebGui < Formula
  url 'file://'+File.expand_path(__FILE__)
  desc 'Dependencies for the WebGui formula'
  sha256 Digest::SHA256.file(File.expand_path(__FILE__)).hexdigest
  version '1'

  depends_on 'libgd'
  depends_on 'ImageMagick'
  depends_on 'pngcrush'
  depends_on 'ensembl/ensembl/zopfli'
  depends_on 'libsass'
  depends_on 'sassc'
  depends_on 'graphviz'

  def install
    File.open('web-gui', 'w') { |file|
      file.write '#!/bin/sh'+"\n"
      deps.each do | dep |
        f = dep.to_formula
        file.write "echo "+[f.full_name, f.version, f.prefix].join("\t")+"\n"
      end
    }
    bin.install 'web-gui'
  end
end
    